"""empty message

Revision ID: 967db4638b37
Revises: 
Create Date: 2024-04-02 14:42:21.526584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967db4638b37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_author', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('post_author')

    # ### end Alembic commands ###
